window.WPA_LIVE_DEMO_ENABLED = true;
window.WPA_LIVE_DEMO_DATA = {
  "mode": "demo",
  "synthetic": true,
  "generated_at": "2026-07-12T10:05:00Z",
  "notice": "Synthetic local demonstration data. Not live news.",
  "total": 12,
  "items": [
    {"id":"demo-protocol-001","title":"DEMO: Official visit programme confirms ceremonial sequence and delegation order","source":"WPA Demo Official Institution","source_type":"official","source_category":"protocol","original_url":"https://example.invalid/wpa-demo/protocol-001","published_at":"2026-07-12T10:00:00Z","fetched_at":"2026-07-12T10:01:00Z","country":"North Macedonia","region":"Balkans","language":"en","primary_category":"protocol","signals":["protocol","institutional"],"summary":"Synthetic demonstration item showing how a protocol-related public-source update would appear. It is not a real news report.","relevance_score":92,"source_confidence":95,"verification_status":"demo_synthetic","human_review":false,"summary_mode":"demo","status":"published","sande_review_status":"rules_ready"},
    {"id":"demo-diplomacy-001","title":"DEMO: Foreign ministries announce a new round of bilateral consultations","source":"WPA Demo Foreign Ministry","source_type":"mfa","source_category":"diplomacy","original_url":"https://example.invalid/wpa-demo/diplomacy-001","published_at":"2026-07-12T09:50:00Z","fetched_at":"2026-07-12T09:51:00Z","country":"France","region":"Europe","language":"en","primary_category":"diplomacy","signals":["institutional"],"summary":"Synthetic demonstration of a diplomatic consultation notice, designed only for local interface testing.","relevance_score":89,"source_confidence":94,"verification_status":"demo_synthetic","human_review":false,"summary_mode":"demo","status":"published","sande_review_status":"rules_ready"},
    {"id":"demo-security-001","title":"DEMO: Multilateral statement links resilience, humanitarian access and public communication","source":"WPA Demo International Organization","source_type":"international_organization","source_category":"security","original_url":"https://example.invalid/wpa-demo/security-001","published_at":"2026-07-12T09:35:00Z","fetched_at":"2026-07-12T09:36:00Z","country":"","region":"Global","language":"en","primary_category":"security","signals":["security","institutional"],"summary":"Synthetic security-aware example. It contains no classified information and is not an intelligence assessment.","relevance_score":87,"source_confidence":93,"verification_status":"demo_synthetic","human_review":false,"summary_mode":"demo","status":"published","sande_review_status":"rules_ready"},
    {"id":"demo-communication-001","title":"DEMO: Institution revises crisis-message sequence after public response review","source":"WPA Demo Communication Office","source_type":"official","source_category":"communication","original_url":"https://example.invalid/wpa-demo/communication-001","published_at":"2026-07-12T09:20:00Z","fetched_at":"2026-07-12T09:21:00Z","country":"Germany","region":"Europe","language":"en","primary_category":"communication","signals":["pr"],"summary":"Synthetic public communication example used to demonstrate message-discipline and crisis-communication filters.","relevance_score":85,"source_confidence":91,"verification_status":"demo_synthetic","human_review":false,"summary_mode":"demo","status":"published","sande_review_status":"rules_ready"},
    {"id":"demo-economic-001","title":"DEMO: Development institution outlines resilience-financing priorities","source":"WPA Demo Development Bank","source_type":"economic_diplomacy","source_category":"diplomacy","original_url":"https://example.invalid/wpa-demo/economic-001","published_at":"2026-07-12T09:05:00Z","fetched_at":"2026-07-12T09:06:00Z","country":"","region":"Global","language":"en","primary_category":"diplomacy","signals":["economic","institutional"],"summary":"Synthetic economic-diplomacy example for testing the Journal Live cards and Analysis Lab workflow.","relevance_score":83,"source_confidence":92,"verification_status":"demo_synthetic","human_review":false,"summary_mode":"demo","status":"published","sande_review_status":"rules_ready"},
    {"id":"demo-interview-001","title":"DEMO: Ambassador interview focuses on trust, tone and institutional clarity","source":"WPA Demo Media Network","source_type":"media","source_category":"communication","original_url":"https://example.invalid/wpa-demo/interview-001","published_at":"2026-07-12T08:50:00Z","fetched_at":"2026-07-12T08:51:00Z","country":"United States","region":"North America","language":"en","primary_category":"communication","signals":["interview","pr"],"summary":"Synthetic interview-watch item demonstrating public presence, message discipline and source attribution.","relevance_score":81,"source_confidence":82,"verification_status":"demo_synthetic","human_review":false,"summary_mode":"demo","status":"published","sande_review_status":"rules_ready"},
    {"id":"demo-social-mastodon","title":"DEMO: Diplomatic institution publishes a public update on a federated social platform","source":"WPA Demo Mastodon Monitor","source_type":"social_platform","source_category":"communication","original_url":"https://example.invalid/wpa-demo/mastodon","published_at":"2026-07-12T08:35:00Z","fetched_at":"2026-07-12T08:36:00Z","country":"","region":"Global","language":"en","primary_category":"communication","signals":["pr","institutional"],"summary":"Synthetic social-platform example. The production registry treats only verified feed or API adapters as active.","relevance_score":78,"source_confidence":70,"verification_status":"demo_synthetic","human_review":false,"summary_mode":"demo","status":"published","sande_review_status":"rules_ready"},
    {"id":"demo-social-bluesky","title":"DEMO: Public diplomacy discussion trends across an open social protocol","source":"WPA Demo Bluesky Monitor","source_type":"social_platform","source_category":"diplomacy","original_url":"https://example.invalid/wpa-demo/bluesky","published_at":"2026-07-12T08:20:00Z","fetched_at":"2026-07-12T08:21:00Z","country":"","region":"Global","language":"en","primary_category":"diplomacy","signals":["institutional","pr"],"summary":"Synthetic adapter demonstration only. It does not claim that a universal RSS feed exists for the platform.","relevance_score":76,"source_confidence":65,"verification_status":"demo_synthetic","human_review":false,"summary_mode":"demo","status":"published","sande_review_status":"rules_ready"},
    {"id":"demo-social-truth","title":"DEMO: Political communication post requires source and context verification","source":"WPA Demo Truth Social Watch","source_type":"social_platform","source_category":"communication","original_url":"https://example.invalid/wpa-demo/truth-social","published_at":"2026-07-12T08:05:00Z","fetched_at":"2026-07-12T08:06:00Z","country":"United States","region":"North America","language":"en","primary_category":"communication","signals":["pr"],"summary":"Synthetic Truth Social example. Production ingestion remains disabled until a lawful, stable and verified adapter is configured.","relevance_score":72,"source_confidence":55,"verification_status":"demo_synthetic","human_review":false,"summary_mode":"demo","status":"published","sande_review_status":"rules_ready"},
    {"id":"demo-social-rumble","title":"DEMO: Video commentary is flagged for attribution and editorial-context review","source":"WPA Demo Rumble Watch","source_type":"social_platform","source_category":"communication","original_url":"https://example.invalid/wpa-demo/rumble","published_at":"2026-07-12T07:50:00Z","fetched_at":"2026-07-12T07:51:00Z","country":"United States","region":"North America","language":"en","primary_category":"communication","signals":["pr"],"summary":"Synthetic Rumble example. It demonstrates the disabled experimental-adapter policy and mandatory human verification.","relevance_score":70,"source_confidence":50,"verification_status":"demo_synthetic","human_review":false,"summary_mode":"demo","status":"published","sande_review_status":"rules_ready"},
    {"id":"demo-justice-001","title":"DEMO: Court communication creates a legal-diplomatic protocol case","source":"WPA Demo International Court","source_type":"justice","source_category":"diplomacy","original_url":"https://example.invalid/wpa-demo/justice-001","published_at":"2026-07-12T07:35:00Z","fetched_at":"2026-07-12T07:36:00Z","country":"","region":"Global","language":"en","primary_category":"diplomacy","signals":["protocol","institutional"],"summary":"Synthetic legal-diplomatic case for testing formal language, restraint and institutional hierarchy analysis.","relevance_score":82,"source_confidence":94,"verification_status":"demo_synthetic","human_review":false,"summary_mode":"demo","status":"published","sande_review_status":"rules_ready"},
    {"id":"demo-thinktank-001","title":"DEMO: Think-tank brief assesses narrative risk around a regional summit","source":"WPA Demo Think Tank","source_type":"think_tank","source_category":"communication","original_url":"https://example.invalid/wpa-demo/thinktank-001","published_at":"2026-07-12T07:20:00Z","fetched_at":"2026-07-12T07:21:00Z","country":"United Kingdom","region":"Europe","language":"en","primary_category":"communication","signals":["pr","security"],"summary":"Synthetic analysis item demonstrating the distinction between primary official sources and secondary commentary.","relevance_score":79,"source_confidence":75,"verification_status":"demo_synthetic","human_review":false,"summary_mode":"demo","status":"published","sande_review_status":"rules_ready"}
  ]
};

/* Journal-only enhancement chain. X11.8.1 Signal Architecture remains isolated. */
document.write('<script src="noise-hardening.js?v=20260713-r2.1"><\/script>');
document.write('<script src="fusion-lenses.js?v=20260713-x1191"><\/script>');
document.write('<script src="analyst-workflow.js?v=20260713-x1191"><\/script>');
document.write('<script src="x119-editorial-intelligence.js?v=20260713-x1191"><\/script>');
document.write('<script src="analyst-core.js?v=20260713-x1191"><\/script>');
document.write('<script src="analyst-export.js?v=20260713-x1191"><\/script>');
