/* WPA Video v1.1: local facilitator simulator and development session-link builder. No live media backend. */
(function(){'use strict';
var remaining=5400,timer=null,muted=true,hands=[],questions=[],sessionId='';
function q(id){return document.getElementById(id);}function safe(s){return String(s||'').replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function clock(){var m=Math.floor(remaining/60),s=remaining%60;q('clock').textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');}
function policy(cap){cap=Number(cap);if(cap<=50)return'1 host + 1 moderator · open discussion windows · up to 5 breakout groups.';if(cap<=100)return'1 host + 2 moderators · managed Q&A · up to 10 breakout groups.';if(cap<=150)return'1 host + 3 moderators · speaker queue · webinar-style questions.';return'1 host + 4 moderators · strict admission · moderated Q&A · broadcast-style delivery.';}
function agenda(min){var rows=min===90?[[10,'Opening and protocol'],[25,'Core lesson'],[20,'Analysis Lab practicum'],[15,'Moderated Q&A'],[10,'Scenario task'],[10,'Review and next steps']]:min===120?[[15,'Opening and protocol'],[35,'Core lesson'],[30,'Analysis Lab practicum'],[15,'Break'],[15,'Moderated Q&A'],[10,'Review']]:[[20,'Opening'],[50,'Core lesson'],[20,'Break'],[45,'Analysis Lab practicum'],[20,'Group work'],[15,'Moderated Q&A'],[10,'Review']];q('agenda').innerHTML=rows.map(function(r){return'<li><strong>'+r[0]+' min</strong> · '+r[1]+'</li>';}).join('');}
function render(){q('handsCount').textContent=hands.length;q('questionsCount').textContent=questions.length;q('hands').innerHTML=hands.length?hands.map(function(x,i){return'<div>'+safe(x)+' <button data-admit="'+i+'">Admit speaker</button></div>';}).join(''):'<em>No raised hands.</em>';q('questions').innerHTML=questions.length?questions.map(function(x,i){return'<div><strong>'+safe(x.name)+':</strong> '+safe(x.text)+' <button data-answer="'+i+'">Mark answered</button></div>';}).join(''):'<em>No questions.</em>';}
function sid(){return'WPA-'+new Date().toISOString().slice(0,10).replace(/-/g,'')+'-'+Math.random().toString(36).slice(2,8).toUpperCase();}
function buildLink(role){if(!sessionId)sessionId=sid();var expiry=q('expiry').value||'24h',cap=q('capacity').value,dur=q('duration').value;var params=new URLSearchParams({session:sessionId,role:role,capacity:cap,duration:dur,expires:expiry,mode:'development'});return location.origin+'/wpa-video.html?'+params.toString();}
function showLinks(){var roles=[['student','Student'],['observer','Observer'],['professor','Professor'],['moderator','Moderator'],['guest','Guest']];q('sessionCode').textContent=sessionId||(sessionId=sid());q('linkResults').innerHTML=roles.map(function(r){var u=buildLink(r[0]);return'<div class="link-row"><strong>'+r[1]+'</strong><input readonly value="'+safe(u)+'"><button data-copy-link="'+safe(u)+'">Copy</button></div>';}).join('');}
function brief(){return['WPA Video Session',q('topic').value,'Session: '+(sessionId||'not generated'),'Duration: '+q('duration').value+' minutes','Capacity: '+q('capacity').value,'Moderation: '+policy(q('capacity').value),'Analysis Lab: '+location.origin+'/wpaws/diplomatic-analysis-lab/','Boundary: development access link; no live backend, recording or identity verification.'].join('\n');}
function boot(){if(!q('build'))return;agenda(90);clock();q('moderation').textContent=policy(50);q('build').onclick=function(){var d=Number(q('duration').value);remaining=d*60;sessionId=sid();q('capView').textContent=q('capacity').value;q('moderation').textContent=policy(q('capacity').value);agenda(d);clock();showLinks();};q('start').onclick=function(){if(timer)return;timer=setInterval(function(){if(remaining>0){remaining--;clock();}else{clearInterval(timer);timer=null;}},1000);};q('pause').onclick=function(){clearInterval(timer);timer=null;};q('muteAll').onclick=function(){muted=true;q('moderation').textContent='Mute-all requested in facilitator console. Remote enforcement requires approved media backend. '+policy(q('capacity').value);};q('toggleMute').onclick=function(){muted=!muted;q('toggleMute').textContent=muted?'🎙 Unmute self':'🔇 Self mute';};q('raise').onclick=function(){hands.push((q('participant').value||'Student').trim().slice(0,60));render();};q('ask').onclick=function(){var t=q('question').value.trim();if(!t)return;questions.push({name:(q('participant').value||'Student').trim().slice(0,60),text:t.slice(0,500)});q('question').value='';render();};q('lowerAll').onclick=function(){hands=[];render();};q('clearQuestions').onclick=function(){questions=[];render();};q('copyBrief').onclick=function(){navigator.clipboard&&navigator.clipboard.writeText(brief());};q('generateLinks').onclick=function(){sessionId=sid();showLinks();};q('copyInvite').onclick=function(){navigator.clipboard&&navigator.clipboard.writeText(brief()+'\n\n'+Array.from(q('linkResults').querySelectorAll('input')).map(function(i){return i.value;}).join('\n'));};document.addEventListener('click',function(e){var a=e.target.getAttribute('data-admit');if(a!==null){hands.splice(Number(a),1);render();}var z=e.target.getAttribute('data-answer');if(z!==null){questions.splice(Number(z),1);render();}var l=e.target.getAttribute('data-copy-link');if(l&&navigator.clipboard)navigator.clipboard.writeText(l);});render();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
