#!/usr/bin/env python3
"""
WPA AI Translation Auto-Fill Pipeline
World Protocol Academy

Phase 4 foundation:
- Reads missing i18n templates generated by scripts/wpa_i18n_audit.py.
- Uses OpenAI API only when OPENAI_API_KEY is present.
- Writes/updates /locales/<lang>/<page>.json with missing keys.
- Preserves existing human translations.
- Designed for controlled GitHub Actions usage, not uncontrolled browser translation.

Required environment:
  OPENAI_API_KEY

Optional environment:
  WPA_TRANSLATION_MODEL   default: gpt-4.1-mini
  WPA_TRANSLATION_DRY_RUN default: false
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Tuple
from urllib import request, error

from wpa_i18n_audit import audit, set_path, has_path, read_json, deep_merge

LANGUAGE_NAMES = {
    "mk": "Macedonian",
    "en": "English",
    "sq": "Albanian",
    "el": "Greek",
    "sr": "Serbian",
    "hr": "Croatian",
    "bs": "Bosnian",
    "sl": "Slovenian",
    "bg": "Bulgarian",
    "ro": "Romanian",
    "hu": "Hungarian",
    "cs": "Czech",
    "sk": "Slovak",
    "pl": "Polish",
    "de": "German",
    "fr": "French",
    "it": "Italian",
    "es": "Spanish",
    "pt": "Portuguese",
    "nl": "Dutch",
    "sv": "Swedish",
    "no": "Norwegian",
    "da": "Danish",
    "fi": "Finnish",
    "et": "Estonian",
    "lv": "Latvian",
    "lt": "Lithuanian",
    "ru": "Russian",
    "uk": "Ukrainian",
    "tr": "Turkish",
    "ar": "Arabic",
    "he": "Hebrew",
    "fa": "Persian",
    "hi": "Hindi",
    "ur": "Urdu",
    "bn": "Bengali",
    "pa": "Punjabi",
    "ta": "Tamil",
    "te": "Telugu",
    "zh-Hans": "Simplified Chinese",
    "zh-Hant": "Traditional Chinese",
    "ja": "Japanese",
    "ko": "Korean",
    "id": "Indonesian",
    "ms": "Malay",
    "vi": "Vietnamese",
    "sw": "Swahili",
    "am": "Amharic",
    "ha": "Hausa",
    "af": "Afrikaans",
}

RTL_LANGS = {"ar", "he", "fa", "ur"}


def get_path(obj: Dict[str, Any], dotted: str) -> Any:
    cur: Any = obj
    for part in dotted.split("."):
        if not isinstance(cur, dict) or part not in cur:
            return None
        cur = cur[part]
    return cur


def flatten_missing(missing_items) -> Dict[Tuple[str, str], List[str]]:
    grouped: Dict[Tuple[str, str], List[str]] = {}
    for item in missing_items:
        grouped.setdefault((item.language, item.page), [])
        if item.key not in grouped[(item.language, item.page)]:
            grouped[(item.language, item.page)].append(item.key)
    return grouped


def load_source_locale(root: Path, source_language: str, page: str) -> Dict[str, Any]:
    common = read_json(root / "locales" / source_language / "common.json")
    page_json = read_json(root / "locales" / source_language / f"{page}.json")
    return deep_merge(common, page_json)


def load_target_page(root: Path, language: str, page: str) -> Dict[str, Any]:
    return read_json(root / "locales" / language / f"{page}.json")


def write_target_page(root: Path, language: str, page: str, data: Dict[str, Any]) -> None:
    target_dir = root / "locales" / language
    target_dir.mkdir(parents=True, exist_ok=True)
    target_path = target_dir / f"{page}.json"
    target_path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def openai_chat(api_key: str, model: str, messages: List[Dict[str, str]], temperature: float = 0.1) -> str:
    payload = {
        "model": model,
        "messages": messages,
        "temperature": temperature,
        "response_format": {"type": "json_object"},
    }
    req = request.Request(
        "https://api.openai.com/v1/chat/completions",
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with request.urlopen(req, timeout=90) as resp:
            body = resp.read().decode("utf-8")
    except error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"OpenAI API HTTP {exc.code}: {detail}") from exc
    data = json.loads(body)
    return data["choices"][0]["message"]["content"]


def translate_batch(api_key: str, model: str, target_language: str, page: str, values: Dict[str, str]) -> Dict[str, str]:
    language_name = LANGUAGE_NAMES.get(target_language, target_language)
    direction_note = "Use right-to-left language conventions where appropriate." if target_language in RTL_LANGS else "Use left-to-right language conventions."

    system = (
        "You are the official translation engine for World Protocol Academy. "
        "Translate institutional website UI text with a formal academic and diplomatic tone. "
        "Preserve brand names such as World Protocol Academy, WPA, WPA Card, WPAWS, QR, AI. "
        "Preserve HTML tags exactly when present, especially <strong>. "
        "Do not add explanations. Return JSON only."
    )
    user = {
        "target_language_code": target_language,
        "target_language_name": language_name,
        "page": page,
        "style": "formal, institutional, academic, diplomatic, clear",
        "direction_note": direction_note,
        "items": values,
        "required_output": "A JSON object with the same keys and translated string values only."
    }
    content = openai_chat(
        api_key=api_key,
        model=model,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": json.dumps(user, ensure_ascii=False)},
        ],
    )
    parsed = json.loads(content)
    if not isinstance(parsed, dict):
        raise ValueError("AI response was not a JSON object")
    return {str(k): str(v) for k, v in parsed.items() if isinstance(v, (str, int, float))}


def chunk_dict(data: Dict[str, str], size: int) -> List[Dict[str, str]]:
    items = list(data.items())
    return [dict(items[i:i + size]) for i in range(0, len(items), size)]


def main() -> int:
    parser = argparse.ArgumentParser(description="AI-fill missing WPA locale keys.")
    parser.add_argument("--root", default=".", help="Repository root")
    parser.add_argument("--core-only", action="store_true", help="Limit to manifest core_pages")
    parser.add_argument("--languages", default="", help="Comma-separated language codes. Empty = all missing languages")
    parser.add_argument("--pages", default="", help="Comma-separated page names. Empty = all missing pages")
    parser.add_argument("--source-language", default="mk", help="Source language to translate from")
    parser.add_argument("--batch-size", type=int, default=25, help="Keys per AI request")
    parser.add_argument("--dry-run", action="store_true", help="Do not write locale files")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    api_key = os.environ.get("OPENAI_API_KEY", "").strip()
    model = os.environ.get("WPA_TRANSLATION_MODEL", "gpt-4.1-mini").strip()
    dry_run = args.dry_run or os.environ.get("WPA_TRANSLATION_DRY_RUN", "").lower() in {"1", "true", "yes"}

    if not api_key:
        print("OPENAI_API_KEY is not set. Skipping AI translation safely.")
        return 0

    _page_audits, missing, _manifest = audit(root=root, core_only=args.core_only)
    grouped = flatten_missing(missing)

    allowed_languages = {x.strip() for x in args.languages.split(",") if x.strip()}
    allowed_pages = {x.strip() for x in args.pages.split(",") if x.strip()}

    total_written = 0
    total_translated = 0

    for (language, page), keys in sorted(grouped.items()):
        if language == args.source_language:
            continue
        if allowed_languages and language not in allowed_languages:
            continue
        if allowed_pages and page not in allowed_pages:
            continue

        source_locale = load_source_locale(root, args.source_language, page)
        target_page = load_target_page(root, language, page)

        pending: Dict[str, str] = {}
        for key in keys:
            if has_path(target_page, key):
                continue
            source_value = get_path(source_locale, key)
            if isinstance(source_value, str) and source_value.strip():
                pending[key] = source_value

        if not pending:
            continue

        print(f"Translating {len(pending)} keys for {language}/{page} using {model}...")

        for batch in chunk_dict(pending, args.batch_size):
            translated = translate_batch(api_key, model, language, page, batch)
            for key, value in translated.items():
                if key in batch and value.strip():
                    set_path(target_page, key, value)
                    total_translated += 1
            time.sleep(0.4)

        if dry_run:
            print(f"DRY RUN: would write locales/{language}/{page}.json")
        else:
            write_target_page(root, language, page, target_page)
            total_written += 1
            print(f"Wrote locales/{language}/{page}.json")

    print(f"AI translation complete. Files written: {total_written}. Keys translated: {total_translated}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
