(function(){
const RAW=window.WPA_COUNTRY_DATA||[];
const countries=RAW.map(x=>({id:x[0],n:x[1],cap:x[2],continent:x[3],ct:x[4],tags:x[5],type:x[6]}));
let filter='ALL';let favOnly=false;let fav=JSON.parse(localStorage.getItem('wpa-symbols-favs')||'[]');let quiz=[];let qi=0;let score=0;
const nationalDays={mk:['09-08','Independence Day'],us:['07-04','Independence Day'],fr:['07-14','National Day'],cn:['10-01','National Day'],al:['11-28','Flag and Independence Day'],de:['10-03','Unity Day'],it:['06-02','Republic Day'],tr:['10-29','Republic Day']};
function q(id){return document.getElementById(id)}function flag(c){return 'https://flagcdn.com/w320/'+c.id+'.png'}function byId(id){return countries.find(c=>c.id===id)}function isFav(id){return fav.includes(id)}function saveFav(){localStorage.setItem('wpa-symbols-favs',JSON.stringify(fav))}
function renderFilters(){const fs=['ALL','EU','AS','AF','NA','SA','OC','NATO','EU-member','ENTITY'];q('filters').innerHTML=fs.map(f=>'<button class="chip '+(filter===f?'active':'')+'" data-filter="'+f+'">'+f+'</button>').join('')+'<span class="small"><span id="shown">0</span> / '+countries.length+'</span>'}
function visible(){const term=(q('search').value||'').toLowerCase();return countries.filter(c=>{if(favOnly&&!isFav(c.id))return false;if(filter==='NATO'&&!c.tags.includes('NATO'))return false;if(filter==='EU-member'&&!c.tags.includes('EU'))return false;if(filter==='ENTITY'&&c.type!=='protocol-entity')return false;if(['EU','AS','AF','NA','SA','OC'].includes(filter)&&c.ct!==filter)return false;return !term||(c.n+c.cap+c.continent+c.tags.join(' ')).toLowerCase().includes(term)})}
function renderGrid(){const data=visible();q('shown').textContent=data.length;q('grid').innerHTML=data.map(c=>'<article class="card country" data-open="'+c.id+'"><div class="flagwrap"><img src="'+flag(c)+'" loading="lazy" alt=""><button class="fav '+(isFav(c.id)?'on':'')+'" data-fav="'+c.id+'">'+(isFav(c.id)?'♥':'♡')+'</button></div><div class="body"><div class="name">'+c.n+'</div><div class="cap">'+c.cap+' · '+c.continent+'</div>'+c.tags.map(t=>'<span class="tag">'+t+'</span>').join('')+(c.type==='protocol-entity'?'<span class="tag entity">protocol entity</span>':'')+'</div></article>').join('')||'<div class="panel">No results.</div>'}
function renderCotd(){if(!countries.length){q('cotd').innerHTML='<div class="notice">Country data did not load.</div>';return}const c=countries[(new Date().getDate()+new Date().getMonth()*31)%countries.length];q('cotd').innerHTML='<img class="flag" src="'+flag(c)+'" alt=""><div><div class="label">Country of the Day</div><div class="name">'+c.n+'</div><div class="small">'+c.cap+' · '+c.continent+' · <span id="clk"></span></div></div>';setInterval(()=>{const e=q('clk');if(e)e.textContent=new Date().toLocaleTimeString('mk-MK')},1000)}
function renderDays(){let today=new Date();let arr=Object.entries(nationalDays).map(([id,d])=>{let y=today.getFullYear();let dt=new Date(y+'-'+d[0]+'T00:00:00');if(dt<today)dt=new Date((y+1)+'-'+d[0]+'T00:00:00');return{c:byId(id),title:d[1],days:Math.ceil((dt-today)/86400000)}}).sort((a,b)=>a.days-b.days).slice(0,6);q('nextDays').innerHTML=arr.map(x=>(x.c?x.c.n:'—')+': '+x.title+' · '+x.days+' days').join('<br>')}
function renderMetrics(){let cont={};countries.forEach(c=>cont[c.continent]=(cont[c.continent]||0)+1);q('metrics').innerHTML='<div class="metric"><b>'+countries.length+'</b><span>Total entities</span></div><div class="metric"><b>'+Object.keys(cont).length+'</b><span>Continents</span></div><div class="metric"><b>'+countries.filter(c=>c.tags.includes('NATO')).length+'</b><span>NATO tagged</span></div><div class="metric"><b>'+countries.filter(c=>c.tags.includes('EU')).length+'</b><span>EU tagged</span></div><div class="metric"><b>'+countries.filter(c=>c.type==='protocol-entity').length+'</b><span>Protocol entities</span></div><div class="metric"><b>'+fav.length+'</b><span>Favorites</span></div>'}
function renderOrgs(){const orgs=['UN / United Nations','NATO / North Atlantic Treaty Organization','EU / European Union','UNESCO','OSCE','WHO','Red Cross','IOC'];q('orgs').innerHTML=orgs.map(o=>'<div class="org"><b>'+o+'</b><div class="small">Protocol organization profile for educational use.</div></div>').join('')}
function openCountry(id){const c=byId(id);if(!c)return;q('mLabel').textContent=c.type==='protocol-entity'?'Protocol entity / educational reference':'Country protocol card';q('mTitle').textContent=c.n;q('mSub').textContent=c.cap+' · '+c.continent;q('mBody').innerHTML='<div><img class="flag" style="width:100%;height:170px" src="'+flag(c)+'"><div class="notice" style="margin-top:12px">'+(c.type==='protocol-entity'?'Status-sensitive educational reference, not a recognition statement.':'Educational protocol reference for symbols and ceremony.')+'</div></div><div><div class="row"><span>Capital</span><b>'+c.cap+'</b></div><div class="row"><span>Continent</span><b>'+c.continent+'</b></div><div class="row"><span>Tags</span><b>'+(c.tags.join(', ')||'—')+'</b></div><div class="row"><span>Protocol note</span><b>Verify flag order, anthem timing, seating order and precedence before official use.</b></div><button class="btn primary" id="copyBrief">Copy protocol brief</button></div>';q('modal').classList.add('open');q('copyBrief').onclick=()=>navigator.clipboard&&navigator.clipboard.writeText('WPA Protocol Brief\n'+c.n+'\nCapital: '+c.cap+'\nContinent: '+c.continent+'\nEducational public reference.');}
function startQuiz(){quiz=[];qi=0;score=0;for(let i=0;i<20;i++){let c=countries[Math.floor(Math.random()*countries.length)],m=i%3;if(m===0)quiz.push(['Кој е главен град на '+c.n+'?',c.cap,opts('cap',c)]);else if(m===1)quiz.push(['На кој континент е '+c.n+'?',c.continent,opts('continent',c)]);else quiz.push(['Која земја/ентитет има главен град '+c.cap+'?',c.n,opts('n',c)])}showQ()}
function opts(prop,c){return [c[prop],...countries.filter(x=>x.id!==c.id).sort(()=>Math.random()-.5).map(x=>x[prop]).filter((x,i,a)=>a.indexOf(x)===i).slice(0,3)].sort(()=>Math.random()-.5)}
function showQ(){let box=q('quizBox');if(qi>=quiz.length){box.innerHTML='<h3>'+score+'/'+quiz.length+'</h3><p class="small">Local self-assessment only, not a certificate.</p><button class="btn primary" id="startQuiz">Retry</button>';q('startQuiz').onclick=startQuiz;return}let item=quiz[qi];box.innerHTML='<div class="small">Question '+(qi+1)+'/'+quiz.length+' · Score '+score+'</div><h3>'+item[0]+'</h3><div class="qopts">'+item[2].map(o=>'<button class="btn qopt">'+o+'</button>').join('')+'</div>';document.querySelectorAll('.qopt').forEach(b=>b.onclick=()=>{if(b.textContent===item[1])score++;qi++;showQ()})}
function init(){renderFilters();renderCotd();renderDays();renderGrid();renderMetrics();renderOrgs();q('quizBox').innerHTML='<h3>Diplomatic Protocol Quiz</h3><p class="small">20 questions about capitals, continents and protocol entities.</p><button class="btn primary" id="startQuiz">Start Quiz</button>';q('startQuiz').onclick=startQuiz;}
document.addEventListener('click',e=>{let fl=e.target.closest('[data-filter]');if(fl){filter=fl.dataset.filter;renderFilters();renderGrid()}let fv=e.target.closest('[data-fav]');if(fv){fav=isFav(fv.dataset.fav)?fav.filter(x=>x!==fv.dataset.fav):fav.concat(fv.dataset.fav);saveFav();renderGrid();renderMetrics();return}let op=e.target.closest('[data-open]');if(op)openCountry(op.dataset.open)});
q('search').oninput=renderGrid;q('mClose').onclick=()=>q('modal').classList.remove('open');q('themeBtn').onclick=()=>document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'':'dark';q('favOnlyBtn').onclick=()=>{favOnly=!favOnly;renderGrid()};q('compareBtn').onclick=()=>alert('Compare panel is scheduled for Phase 1.1; use two country protocol cards for now.');init();
})();