name = "wpa-virtual-sande-v35-1-staging"
main = "src/index.mjs"
compatibility_date = "2026-07-15"
workers_dev = true
preview_urls = true

[ai]
binding = "AI"

[vars]
AI_SEARCH_NAME = "protocol-ai"
WPA_PUBLIC_ROOT = "https://worldprotocolacademy-code.github.io"
WPA_LIVE_API_ROOT = "https://wpa-live-production-bridge.worldprotocolacademy.workers.dev"
ALLOWED_ORIG