name: DEPLOY Virtual Sande v35.1 PRODUCTION

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: virtual-sande-v35-1-production-deploy
  cancel-in-progress: false

env:
  CERTIFIED_SHA: 6a1822ba8e524a454dcf4a038f3d6bc38c3d500d
 